import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FilterContextProvider } from "./components/Nav/FilterNav/FilterNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GameVis Explorer",
  description: "Generated by create next app",
  authors: [
    { name: "Jessica Chen" },
    { name: "Michael Dresler" },
    { name: "Alireza Karduni" },
    { name: "Jaden Lee" },
    { name: "Nathan Lew" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FilterContextProvider>{children}</FilterContextProvider>
      </body>
    </html>
  );
}
