[
    {'game_id': '67',
 'screenshot_id': '1',
 'vis_id': 'le1',
 'data': [{'data_value': 'Mission player is trying to complete',
   'data_type': 'Nominal'}],
 'marks': ['Rectangle', 'Symbol', 'Text'],
 'channels': [['Text'], ['Shape']],
 'vis_name': 'Mission Details',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Data value is lengthy.']},
 {'game_id': '67',
 'screenshot_id': '1',
 'vis_id': 'l2',
 'data': [{'data_value': 'Objective type, location', 'data_type': 'Nominal'},
  {'data_value': 'Objective type, location', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Shape', ['Hue']]],
 'vis_name': 'Mission Location',
 'vis_usage': ['Game'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'mission',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Tells player where they need to go to progress the mission']},
 {'game_id': '67',
 'screenshot_id': '2',
 'vis_id': 'l1',
 'data': [{'data_value': 'Enemy health, name, and level',
   'data_type': 'Quantitative'}],
 'marks': ['Rectangle'],
 'channels': [['Length'], ['Hue'], ['Text']],
 'vis_name': 'Enemy Information and Health Bar',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'above',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '67',
 'screenshot_id': '2',
 'vis_id': 'l2',
 'data': [{'data_value': 'Ammo count', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Text']],
 'vis_name': 'Ammo count',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'gun',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['DATA VALUE: How much ammo the player has left for the equipped weapon',
  'DATA TYPE: QUANTITATIVE',
  'ENCODING: MARK: Text CHANNEL 1: Text']},
  {'game_id': '67',
 'screenshot_id': '2',
 'vis_id': 'l3',
 'data': [{'data_value': 'Player health, weapon and ammo',
   'data_type': 'Quantitative'}],
 'marks': ['Area', 'Symbol'],
 'channels': [['Length'],
  ['Lightness'],
  ['Text'],
  ['Shape', 'Lightness'],
  ['Text']],
 'vis_name': 'Player health and weapon',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Right'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Empty part of the bar is a bit more transparent.',
  'Info that its a health bar.',
  'How much ammo is left (10).',
  'Max amount of ammo (76).']},
  {'game_id': '67',
 'screenshot_id': '3',
 'vis_id': 'l1',
 'data': [{'data_value': 'Battery life decreases when equipment used',
   'data_type': 'Quantitative'}],
 'marks': ['Rectangle'],
 'channels': [['Length'], ['Luminance'], ['Shape']],
 'vis_name': 'Item battery',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'On the mining tool',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Some equipment have a battery life, once it dies, the item can’t be used.',
  'No opacity means that se.',
  '4 Irregular pentagons act as segments.']},
  {'game_id': '67',
 'screenshot_id': '4',
 'vis_id': 'l1',
 'data': [{'data_value': 'Skill that the player is completing...',
   'data_type': 'Quantitative'}],
 'marks': ['Image', 'Area', 'Text'],
 'channels': [['Length'],
  ['Shape', ['Hue', 'Saturation', 'Lightness']],
  ['Text']],
 'vis_name': 'Skill Progression Details',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Middle', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Data value contains Skill that the player is completing, description, progression.']},
 {'game_id': '67',
 'screenshot_id': '5',
 'vis_id': 'l1a',
 'data': [{'data_value': 'Players can focus on an NPC for more info.',
   'data_type': 'Spatial'}],
 'marks': ['Circle', 'Line'],
 'channels': [['Shape'], ['Position']],
 'vis_name': 'Interactable NPCs',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'item',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['There’s a line that connects this with 3b.']},
 {'game_id': '67',
 'screenshot_id': '5',
 'vis_id': 'l1b',
 'data': [{'data_value': 'Line connects with 3a. Info on who they are and potential interactions',
   'data_type': 'Nominal'}],
 'marks': ['Text', 'Symbol'],
 'channels': [['Text'], ['Symbol']],
 'vis_name': 'NPC information',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'To the right of the NPC',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '67',
 'screenshot_id': '6',
 'vis_id': 'l1',
 'data': [{'data_value': 'minimap, helps players discover new areas, objects, hazards, and enemies',
   'data_type': 'Nominal'},
  {'data_value': 'planet in the middle', 'data_type': 'Temporal'},
  {'data_value': 'stamina bar', 'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Shape', 'Arc'],
 'channels': [['Shape', ['Hue']],
  ['Angle'],
  ['Colour', ['Luminance']],
  ['Length'],
  ['Angle']],
 'vis_name': 'Compass',
 'vis_usage': ['Game'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Acts like a minimap, helps players discover new areas, objects, hazards, and enemies',
  'Blue hexagons --> missions and objectives.',
  'Red markers --> enemies or hostile creatures',
  'Rotates around the compass as you move around within the game',
  'The colour correspond to the time of day, when the black is appearing --> dusk coming',
  'Dark curved fill comes in as it gets darker',
  'Represents the stamina, starts at the left side (o2)']},
  {'game_id': '67',
 'screenshot_id': '7',
 'vis_id': 'l1',
 'data': [{'data_value': 'Screen looks like this when scanning',
   'data_type': 'Quantitative'},
  {'data_value': 'which moon', 'data_type': 'Nominal'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Shape'], ['Text']],
 'vis_name': 'Compass - Scan mode',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Left'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '67',
 'screenshot_id': '7',
 'vis_id': 'l2',
 'data': [{'data_value': 'Info on how much of the planet the player has discovered',
   'data_type': 'Nominal'},
  {'data_value': 'How far along they are', 'data_type': 'Quantitative'}],
 'marks': ['Area', 'Text', 'Symbol'],
 'channels': [['Text'], ['Length']],
 'vis_name': 'Area information',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Middle', 'Left'],
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '67',
 'screenshot_id': '7',
 'vis_id': 'l3',
 'data': [{'data_value': 'Leads player to specified place',
   'data_type': 'Spatial'}],
 'marks': ['Path', 'Symbol'],
 'channels': [['Path'], ['Shape', ['Hue', 'Saturation', 'Lightness']]],
 'vis_name': 'Path to Destination',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'where players need to go',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Glows in and out.']},
 {'game_id': '67',
 'screenshot_id': '7',
 'vis_id': 'l4',
 'data': [{'data_value': 'When using the compass, things that add to area statistic (2) is highlighted',
   'data_type': 'Nominal'}],
 'marks': ['Area'],
 'channels': [['Shape'], ['Lightness'], ['Position']],
 'vis_name': 'Environmental Items',
 'vis_usage': ['Environment'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'item',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '67',
 'screenshot_id': '8',
 'vis_id': 'l1',
 'data': [{'data_value': 'Overall stats on the ship (speed, weapon stuff)',
   'data_type': 'Nominal'}],
 'marks': ['Circle', 'Area', 'Arc'],
 'channels': [['Shape'], ['Text'], ['Length']],
 'vis_name': 'Ship stats',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Middle', 'Middle'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['DATA VALUE: Different categories. ENCODING: What key to click to use it. Different thickness of lines indicate a weapon on the circular menu.']},
 {'game_id': '67',
 'screenshot_id': '8',
 'vis_id': 'l2',
 'data': [{'data_value': 'Customizable, limit on recharge',
   'data_type': 'Quantitative'}],
 'marks': ['Arc'],
 'channels': [['Angle'], ['Text']],
 'vis_name': 'Ship weapons',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'user setup',
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['When bar is depleted, it’ll slowly fill itself again after time.']},
 {'game_id': '67',
 'screenshot_id': '8',
 'vis_id': 'l3',
 'data': [{'data_value': 'Customizable, usually if its related to movement, players have to adjust manually how much of the value they want',
   'data_type': 'Quantitative'}],
 'marks': ['Arc'],
 'channels': [['Angle'], ['Hue'], ['Text']],
 'vis_name': 'Ship boost',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'weapons',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['It’s also patterned so its easy to differentiate from weapons',
  'More detailed info on how much is left (100, 50, etc)']},
  {'game_id': '67',
 'screenshot_id': '8',
 'vis_id': 'l4',
 'data': [{'data_value': 'Health', 'data_type': 'Quantitative'}],
 'marks': ['Rectangle', 'Text'],
 'channels': [['Length'], ['Text']],
 'vis_name': 'Ship health',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Right'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['DATA VALUE: How much health the ship has left',
  'MARK: Bar with text',
  'CHANNEL 1: Length: Health they have',
  'CHANNEL 2: Text: Specific number on how much health they have']},
  {'game_id': '67',
 'screenshot_id': '9',
 'vis_id': 'l1a',
 'data': [{'data_value': 'Targeting enemy', 'data_type': 'Nominal'}],
 'marks': ['Symbol'],
 'channels': [['Shape'], ['Position']],
 'vis_name': 'Target selector',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'enemy',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Players can target a specific enemy to shoot at, reticle']},
 {'game_id': '67',
 'screenshot_id': '9',
 'vis_id': 'l1b',
 'data': [{'data_value': 'Enemy Name', 'data_type': 'Nominal'},
  {'data_value': 'Enemy health', 'data_type': 'Quantitative'},
  {'data_value': 'Distance', 'data_type': 'Quantitative'}],
 'marks': ['Rectangle', 'Text'],
 'channels': [['Length'], ['Text']],
 'vis_name': 'Enemy Health',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'To the right of the ship',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
    {'game_id': '68',
 'screenshot_id': '1',
 'vis_id': 'l1',
 'data': [{'data_value': 'Location, attributes', 'data_type': 'Spatial'},
  {'data_value': 'Location, attributes', 'data_type': 'Nominal'}],
 'marks': ['Circle'],
 'channels': [['Position'], [['Hue', 'Luminance']]],
 'vis_name': 'Hiding area',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'thing the game wants you to interact with',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Where the players can hide, 1a will always show up when this shows up.']},
 {'game_id': '68',
 'screenshot_id': '1',
 'vis_id': 'l2',
 'data': [{'data_value': 'Terrain, player pos', 'data_type': 'Spatial'}],
 'marks': ['Area', 'Symbol'],
 'channels': [['Hue', 'Lightness'],
  ['Shape'],
  ['Position'],
  ['Angle'],
  ['Hue', 'Shape']],
 'vis_name': 'Minimap',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Right'],
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ["Lets players see where they are & general info on how the 'dungeon' is like.",
  'Separate current floor from other areas.',
  'Where is player looking.',
  'Red Identity vs. Yellow point of interest.']},
  {'game_id': '68',
 'screenshot_id': '1',
 'vis_id': 'l3',
 'data': [{'data_value': 'health', 'data_type': 'Quantitative'},
  {'data_value': 'sp', 'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Rectangle'],
 'channels': [['Length'],
  ['Color'],
  ['Shape', ['Hue', 'Saturation', 'Lightness']]],
 'vis_name': 'Player stats',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Right'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Simplified version of the players stats.',
  'Blue for health, Pink for SP (works like mana).',
  'Who the character is.']},
  {'game_id': '68',
 'screenshot_id': '1',
 'vis_id': 'l4',
 'data': [{'data_value': 'Current mission', 'data_type': 'Nominal'}],
 'marks': ['Rectangle', 'Text'],
 'channels': [['Text']],
 'vis_name': 'Current mission',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Right'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Mission player needs to complete']},
 {'game_id': '68',
 'screenshot_id': '2',
 'vis_id': 'l1',
 'data': [{'data_value': 'Date', 'data_type': 'Temporal'}],
 'marks': ['Text'],
 'channels': [['Text'], ['Hue']],
 'vis_name': 'In-game date',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Date affects what actions players can do (eg. go to school, is shops open or not) and deadlines for some mission']},
 {'game_id': '68',
 'screenshot_id': '2',
 'vis_id': 'l2',
 'data': [{'data_value': 'Available conversation/interaction type',
   'data_type': 'Nominal'},
  {'data_value': 'position', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Shape']],
 'vis_name': 'Interaction Indicator',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above the thing that’s interactable',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['If there’s a thing / character the player can interact with, an icon will show up indicating the action. In this case, its a conversation.']},
 {'game_id': '68',
 'screenshot_id': '2',
 'vis_id': 'l3',
 'data': [{'data_value': 'Map region name', 'data_type': 'Nominal'}],
 'marks': ['Rectangle', 'Text'],
 'channels': [['Text']],
 'vis_name': 'Area the player is in',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Right'],
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Tells player where exactly in the world they are']},
 {'game_id': '68',
 'screenshot_id': '3',
 'vis_id': 'l1a',
 'data': [{'data_value': 'Chosen enemy slot', 'data_type': 'Ordinal'},
  {'data_value': 'health', 'data_type': 'Quantitative'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Length']],
 'vis_name': 'Targeting enemy',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'The middle of the enemy, right on top',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Players can target a specific enemy to attack, will prompt (1b) to show up. Doing this will also show the enemy’s health.']},
 {'game_id': '68',
 'screenshot_id': '3',
 'vis_id': 'l1b',
 'data': [{'data_value': 'Name of enemy', 'data_type': 'Nominal'}],
 'marks': ['Text'],
 'channels': [['Text']],
 'vis_name': 'Enemy that’s targeted',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '68',
 'screenshot_id': '3',
 'vis_id': 'l2',
 'data': [{'data_value': 'Party member name', 'data_type': 'Nominal'},
  {'data_value': 'Slot', 'data_type': 'Ordinal'},
  {'data_value': 'Health', 'data_type': 'Quantitative'},
  {'data_value': 'SP', 'data_type': 'Quantitative'},
  {'data_value': 'Selected member', 'data_type': 'Ordinal'}],
 'marks': ['Image', 'Area', 'Text'],
 'channels': [['Size'], ['Shape', 'Hue'], ['Hue'], ['Text'], ['Length']],
 'vis_name': 'Player stats',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Right'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['The character that’s attacking will always be a bit bigger in scale and a bit more to the left.']},
 {'game_id': '68',
 'screenshot_id': '4',
 'vis_id': 'l1a',
 'data': [{'data_value': 'Available attack name', 'data_type': 'Nominal'},
  {'data_value': 'damage type', 'data_type': 'Nominal'},
  {'data_value': 'stat required', 'data_type': 'Nominal'},
  {'data_value': 'stat required usage', 'data_type': 'Quantitative'}],
 'marks': ['Area', 'Text', 'Symbol'],
 'channels': [['Position'], ['Text'], ['Shape', 'Hue']],
 'vis_name': 'Attack options',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['On their action, players can chose what to do. Attacks have requirements on how they can be used (eg. takes 106 health from the player when used).',
  'Different icons for different attack types and the category of attack (seemingly) is differentiated by the color.']},
  {'game_id': '68',
 'screenshot_id': '4',
 'vis_id': 'l1b',
 'data': [{'data_value': 'Damage type', 'data_type': 'Nominal'},
  {'data_value': 'strength', 'data_type': 'Ordinal'},
  {'data_value': 'target count', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Text']],
 'vis_name': 'Attack information',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Left'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Info on what exactly the attack is, doesn’t tell you how much it’ll deal exactly']},
 {'game_id': '68',
 'screenshot_id': '5',
 'vis_id': 'le1',
 'data': [{'data_value': 'Damage dealt, remaining health',
   'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Text'], ['Length']],
 'vis_name': 'Damage dealt',
 'vis_usage': ['Enemy', 'Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': "enemy's right",
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Amount of damage the enemy received, also shows players how much left they more or less have left',
  'How filled in the heart is']},
  {'game_id': '68',
 'screenshot_id': '6',
 'vis_id': 'le1',
 'data': [{'data_value': 'Damage dealt', 'data_type': 'Quantitative'},
  {'data_value': 'damage type', 'data_type': 'Nominal'}],
 'marks': ['Text'],
 'channels': [['Text']],
 'vis_name': 'Critical damage',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'enemy’s health bar',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Crit increases the damage the attack deals']},
 {'game_id': '68',
 'screenshot_id': '7',
 'vis_id': 'l1a',
 'data': [{'data_value': 'Action type', 'data_type': 'Nominal'}],
 'marks': ['Text'],
 'channels': [['Text'], ['Luminance']],
 'vis_name': 'Enemy action',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above the enemy health bar, sometimes overlapping',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['When its the enemy’s turn, there will a pop-up telling players what the enemy’s doing.',
  'Ensures the player notices it.']},
  {'game_id': '68',
 'screenshot_id': '7',
 'vis_id': 'l1b',
 'data': [{'data_value': 'Damage received', 'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Text'], ['Length']],
 'vis_name': 'Damage received',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'To the characters right',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['There is no difference from on how this info is presented vs when the player damages an enemy. Only the (1a) pop up thing']}
 ,
{'game_id': '69',
 'screenshot_id': '1',
 'vis_id': 'l1',
 'data': [{'data_value': 'Players health', 'data_type': 'Quantitative'},
  {'data_value': 'money (geo)', 'data_type': 'Quantitative'},
  {'data_value': 'healing (circle)', 'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Text', 'Symbol', 'Circle'],
 'channels': [['Length'], ['Luminance'], ['Text'], ['Length']],
 'vis_name': 'Health bar and currency',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Healing bar (circle) slowly fills up, once full, players can heal.']},
 {'game_id': '69',
 'screenshot_id': '2',
 'vis_id': 'l1',
 'data': [{'data_value': 'Battle timer', 'data_type': 'Nominal'}],
 'marks': ['Text'],
 'channels': [['Text']],
 'vis_name': 'Boss battle',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Right'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Time = 0',
  'The boss’s name will appear when player is in that area']},
  {'game_id': '69',
 'screenshot_id': '3',
 'vis_id': 'l1',
 'data': [{'data_value': 'Achievement', 'data_type': 'Nominal'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Shape'], ['Text']],
 'vis_name': 'Achievement',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Middle', 'Left'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Appears when completing an achievement',
  'Each achievement has its own icon']},
  {'game_id': '69',
 'screenshot_id': '3',
 'vis_id': 'l2',
 'data': [{'data_value': 'Item gained', 'data_type': 'Nominal'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Shape', ['Hue', 'Saturation', 'Lightness']], ['Text']],
 'vis_name': 'Item gained',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Left'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Pops up when players find an item']},
 {'game_id': '69',
 'screenshot_id': '4',
 'vis_id': 'l1',
 'data': [{'data_value': 'Charm selected', 'data_type': 'Nominal'},
  {'data_value': 'Slot number', 'data_type': 'Ordinal'},
  {'data_value': 'Notch count', 'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Text', 'Circle'],
 'channels': [['Shape', ['Hue', 'Saturation', 'Lightness']], ['Length']],
 'vis_name': 'Equipment',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['The characters main thing is using different charms to match their strategy and optimize gameplay.',
  'Each charm has a cost and players can only equip a certain amount of charms depending on their available slot & notches (the cost of each charm).',
  'Identify used vs. remaining notches to know if charms can be equipped or not.',
  'The glowing circle for how many more notches players have, (the one with no glow means its already used up).',
  "The circle in the equipped section means players can still equip 1 more charm (if they also have enough notches players don't have yet)."]},
{'game_id': '69',
 'screenshot_id': '4',
 'vis_id': 'l2',
 'data': [{'data_value': 'charm found', 'data_type': 'Nominal'},
  {'data_value': 'slot', 'data_type': 'Ordinal'}],
 'marks': ['Symbol'],
 'channels': [['Position'],
  ['Shape', ['Hue', 'Saturation', 'Lightness']],
  ['Length']],
 'vis_name': 'Available charms',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['All the charms (equipment) the player owns is visible here, each has their own thing.',
  'Charms that aren’t discovered yet just have a circle occupying their space.']},
  {'game_id': '69',
 'screenshot_id': '4',
 'vis_id': 'l3a',
 'data': [{'data_value': 'Player cursor', 'data_type': 'Spatial'}],
 'marks': ['Area', 'Symbol'],
 'channels': [['Position']],
 'vis_name': 'Charm selector',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Player controlled',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Hovering over the charm to get more info from it',
  'The white border around the charm + the blue glow around the charm']},
  {'game_id': '69',
 'screenshot_id': '4',
 'vis_id': 'l3b',
 'data': [{'data_value': 'Name', 'data_type': 'Nominal'},
  {'data_value': 'details', 'data_type': 'Nominal'},
  {'data_value': 'notch cost', 'data_type': 'Quantitative'}],
 'marks': ['Image', 'Text', 'Circle'],
 'channels': [['Shape', ['Hue', 'Saturation', 'Lightness']],
  ['Text'],
  ['Length']],
 'vis_name': 'Charm details',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Middle', 'Right'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Info on what the charm selected from (3a) does and how much it costs to equip t']},
 {'game_id': '69',
 'screenshot_id': '4',
 'vis_id': 'l4',
 'data': [{'data_value': 'charms equipped', 'data_type': 'Nominal'}],
 'marks': ['Circle'],
 'channels': [['Lightness']],
 'vis_name': 'Equipped charm',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'player controlled',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['DATA VALUE: The charms the player has equipped']},
 {'game_id': '69',
 'screenshot_id': '5',
 'vis_id': 'l1',
 'data': [{'data_value': 'By entering specific parts',
   'data_type': 'Spatial'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Angle'], ['Text']],
 'vis_name': 'Adjacent areas',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'area',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['The arrow above the text means that it’ll bring the player to a diff area']},
 {'game_id': '69',
 'screenshot_id': '5',
 'vis_id': 'l2',
 'data': [{'data_value': 'Place name', 'data_type': 'Nominal'},
  {'data_value': 'position', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Shape', 'Hue']],
 'vis_name': 'Map pins',
 'vis_usage': ['Environment'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Point of Interest',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Places of interest on the map',
  'Different icons & color type = different things (eg. bench --> save, orange icons --> different stores)']},
  {'game_id': '69',
 'screenshot_id': '5',
 'vis_id': 'l3',
 'data': [{'data_value': 'Boss type, location', 'data_type': 'Nominal'},
  {'data_value': 'Boss type, location', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Size'], ['Shape']],
 'vis_name': 'Final boss battle',
 'vis_usage': ['Game'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'on their spot in the map',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Unlocking this area unlocks the final boss (and later lets players repeat some old miniboss fights)',
  'Higher attention in hierarchy draws player towards important event']}
    ,

{'game_id': '70',
 'screenshot_id': '1',
 'vis_id': 'l1a',
 'data': [{'data_value': 'Mission location', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Luminance'], ['Shape']],
 'vis_name': 'Mission Location',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'direction of objective',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '70',
 'screenshot_id': '1',
 'vis_id': 'l1b',
 'data': [{'data_value': 'Mission location', 'data_type': 'Spatial'}],
 'marks': ['Line', 'Symbol', 'Text'],
 'channels': [['Position'], ['Shape'], ['Text']],
 'vis_name': 'Mission distance',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Middle'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Precisely identify where the icon is located determines where the player needs to go (left, right, or forward)',
  'What players need to look at to know where to go']},
  {'game_id': '70',
 'screenshot_id': '2',
 'vis_id': 'l1',
 'data': [{'data_value': 'Objective time remaining',
   'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Text']],
 'vis_name': 'Timer',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Middle'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '70',
 'screenshot_id': '3',
 'vis_id': 'l1',
 'data': [{'data_value': 'Where the player is located',
   'data_type': 'Spatial'}],
 'marks': ['Text'],
 'channels': [['Luminance'], ['Text']],
 'vis_name': 'Location',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': ['Local', False],
 'notes': ['Identify selected state', 'Precisely get location']},
 {'game_id': '70',
 'screenshot_id': '3',
 'vis_id': 'l2a',
 'data': [{'data_value': 'Mission Location', 'data_type': 'Spatial'},
  {'data_value': 'Quest name/id', 'data_type': 'Ordinal'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Position'], ['Shape', ['Hue']]],
 'vis_name': 'Mission Location',
 'vis_usage': ['Game'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'mission location',
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Where a mission is located, what is it.',
  'Depending on the mission, I think the color also changes.']},
  {'game_id': '70',
 'screenshot_id': '3',
 'vis_id': 'l2b',
 'data': [{'data_value': 'Mission goals', 'data_type': 'Nominal'},
  {'data_value': 'Progress', 'data_type': 'Quantitative'}],
 'marks': ['Rectangle', 'Symbol', 'Text'],
 'channels': [['Text'], ['Shape', ['Saturation', 'Hue']]],
 'vis_name': 'Mission details',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Tells players which button on the controller to click to do specific actions',
  'Also helps differentiate the heading with body']},
  {'game_id': '70',
 'screenshot_id': '3',
 'vis_id': 'l1',
 'data': [{'data_value': 'Player position', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Shape', 'Luminance']],
 'vis_name': 'Player position',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'mission',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Slight glow around the icon']},
 {'game_id': '70',
 'screenshot_id': '4',
 'vis_id': 'l1',
 'data': [{'data_value': 'Where the player is located within whole city',
   'data_type': 'Spatial'}],
 'marks': ['Path', 'Line', 'Text'],
 'channels': [['Saturation', 'Luminance'], ['Position'], ['Text']],
 'vis_name': 'Player position',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Player location',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['The area that the player is in is coloured in',
  'The pop-up with the text of where the player is at has a blue bg colour too to help it show up']},
  {'game_id': '70',
 'screenshot_id': '5',
 'vis_id': 'le1',
 'data': [{'data_value': 'Status effect', 'data_type': 'Nominal'}],
 'marks': ['Text'],
 'channels': [['Text']],
 'vis_name': 'Special Attack used',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above player character',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '70',
 'screenshot_id': '5',
 'vis_id': 'l2',
 'data': [{'data_value': 'Enemy health', 'data_type': 'Quantitative'}],
 'marks': ['Rectangle'],
 'channels': [['Length'], [['Hue']], ['Text']],
 'vis_name': 'Enemy Health Bar',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above enemy',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Bar under the health is for a status effect, fills up as the enemy gets hit.',
  'The damage they receive is in red and it’ll deplete the bar by that much.']},
  {'game_id': '70',
 'screenshot_id': '5',
 'vis_id': 'l3',
 'data': [{'data_value': 'Target specific enemy', 'data_type': 'Nominal'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Text']],
 'vis_name': 'Targeting enemy',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Middle of enemy',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Players can target a specific enemy to fight with',
  'Says locked on']},
  {'game_id': '70',
 'screenshot_id': '6',
 'vis_id': 'l1',
 'data': [{'data_value': 'Damage from enemy', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Hue'], ['Text']],
 'vis_name': 'Damage received',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above the character',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['DATA TYPE: QUANTITATIVE',
  'ENCODING: Distinguish health update from heal',
  'Get precise value']},
  {'game_id': '70',
 'screenshot_id': '6',
 'vis_id': 'le2',
 'data': [{'data_value': 'Status effect (pressure)', 'data_type': 'Nominal'}],
 'marks': ['Text'],
 'channels': [['Length'], ['Text']],
 'vis_name': 'Pressure effect',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Under enemy health bar',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['When players hit a critical attack / uses a magic element the enemy is weak to, this effect can happen.',
  'The bar slowly builds up to, when full it’ll change the effect to staggered.']},
  {'game_id': '70',
 'screenshot_id': '7',
 'vis_id': 'le1',
 'data': [{'data_value': 'Healing amount', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Hue'], ['Text']],
 'vis_name': 'Healing',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Middle of player character',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Differentiate from damage received.', 'Get precise value.']},
 {'game_id': '70',
 'screenshot_id': '8',
 'vis_id': 'le1',
 'data': [{'data_value': 'Boss special move', 'data_type': 'Nominal'}],
 'marks': ['Text'],
 'channels': [['Text'], ['Lightness']],
 'vis_name': 'Boss special action',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above the enemy health bar, sometimes overlapping',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Bosses always have a special move that they can do, when that happens, a text above them will appear telling players it happening to give them time to dodge.',
  'Ensures the player notices it']},
  {'game_id': '70',
 'screenshot_id': '8',
 'vis_id': 'le2',
 'data': [{'data_value': 'Physical damage', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Text'], ['Hue']],
 'vis_name': 'Damage dealt',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'wherever the attack hits the enemy',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Damage dealt by the characters from melee attacks (or guns!)']},
 {'game_id': '70',
 'screenshot_id': '8',
 'vis_id': 'l3',
 'data': [{'data_value': 'Health, MP, ATB, Limit',
   'data_type': 'Quantitative'}],
 'marks': ['Text', 'Area'],
 'channels': [['Text'], ['Length'], ['Hue', 'Saturation', 'Lightness']],
 'vis_name': 'Player stats',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Right'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Players can see info on the characters in their team. The one the player is controlling will always have their stats card be a bit bigger and below all the other ones.',
  'Shows how much of each thing the players have (eg. how much health, how much mp, the ATB value).',
  'Differentiate each thing with each other, helps it stand out.']},
  {'game_id': '70',
 'screenshot_id': '9',
 'vis_id': 'l1',
 'data': [{'data_value': 'Stagger progress', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Length'], ['Text']],
 'vis_name': 'Staggered effect',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Under the enemy’s health bar',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Happens when the bar under the health is filled up. Increases the chance of enemies getting stunned + increases damage received.']},
 {'game_id': '70',
 'screenshot_id': '9',
 'vis_id': 'l1',
 'data': [{'data_value': 'Magic damage type, amount', 'data_type': 'Nominal'},
  {'data_value': 'Magic damage type, amount', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Text'], ['Hue']],
 'vis_name': 'Magic damage dealt',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above the enemy getting attacked',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Damage dealt by the characters from spells']}
    ,
{'game_id': '71',
 'screenshot_id': '1',
 'vis_id': 'g1',
 'data': [{'data_value': 'Areas available', 'data_type': 'Ordinal'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Position'], ['Length'], ['Hue'], ['Shape']],
 'vis_name': 'Area Select',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Middle'],
   'coords': 'World'}],
 'vis_visibility': [['Global', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '1',
 'vis_id': 'g2',
 'data': [{'data_value': 'Total moons collected',
   'data_type': 'Quantitative'}],
 'marks': ['Rectangle', 'Text'],
 'channels': [['Text']],
 'vis_name': 'Total moons collected',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Right'],
   'coords': 'Camera'}],
 'vis_visibility': [['Global', False]],
 'notes': ['The total amount of moons collected across all stages']},
 {'game_id': '71',
 'screenshot_id': '2',
 'vis_id': 'l1a',
 'data': [{'data_value': 'Current location of player', 'data_type': 'Spatial'},
  {'data_value': 'orientation', 'data_type': 'Spatial'}],
 'marks': ['Symbol', 'Area'],
 'channels': [['Position'], ['Angle'], ['Shape']],
 'vis_name': 'Player Pointer',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Based on player position',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '2',
 'vis_id': 'l1b',
 'data': [{'data_value': 'Name of viewpoint',
   'data_type': 'Spatial'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Position'], ['Text'], ['Shape']],
 'vis_name': 'Active hovered viewpoint',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Location of selected',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['The name of the viewpoint with instructions on button control to fast warp to that area.']},
 {'game_id': '71',
 'screenshot_id': '2',
 'vis_id': 'l1c',
 'data': [{'data_value': 'Next objective position', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Shape']],
 'vis_name': 'Next objective',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Location of the main objective',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '3',
 'vis_id': 'g1',
 'data': [{'data_value': 'Total number of coins',
   'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Text'], ['Shape']],
 'vis_name': 'Global Coin counter',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'World'}],
 'vis_visibility': [['Global', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '3',
 'vis_id': 'l1',
 'data': [{'data_value': 'Total number of local...coins owned',
   'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Text'], ['Shape']],
 'vis_name': 'Local Currency counter',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '3',
 'vis_id': 'l2',
 'data': [{'data_value': 'Total amount of moons collected and remaining',
   'data_type': 'Quantitative'}],
 'marks': ['Symbol'],
 'channels': [['Shape'], ['Position']],
 'vis_name': 'Moon counter',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '3',
 'vis_id': 'le3',
 'data': [{'data_value': 'Health', 'data_type': 'Quantitative'}],
 'marks': ['Arc', 'Text'],
 'channels': [['Angle'], ['Text'], ['Hue']],
 'vis_name': 'Health Point Meter',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'above character when damaged',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Cyclic bar with text (QUANTITATIVE value) in the middle.',
  'Dotted line circle represents the empty slot.',
  'Number value of health points left.',
  'Blue: extra health points.',
  'Green: Good amount of health left (more than 50%).',
  'Yellow: Moderate amount of health left (less than 50%).',
  'Red: Low amount of health left (less than 25%).']},
  {'game_id': '71',
 'screenshot_id': '3',
 'vis_id': 'l4',
 'data': [{'data_value': 'Player orientation', 'data_type': 'Ordinal'}],
 'marks': ['Area'],
 'channels': [['Angle']],
 'vis_name': 'Compass',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Right'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '4',
 'vis_id': 'le1',
 'data': [{'data_value': 'Direction/final end point of Chain Chomp release',
   'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Length'], ['Angle'], ['Animation']],
 'vis_name': 'Chain Chomps Directional Line',
 'vis_usage': ['Game'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Player',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['MARK: Repeating chevron SYMBOLS along a PATH',
  'Arrows slowly animated in a loop towards the direction it’s facing']}
]