[
  {
    game_id: "71",
    screenshot_id: "1",
    vis_id: "g1",
    data: [[{ data_value: "Areas", data_type: "Ordinal" }]],
    marks: [["Symbol", "Text"]],
    channels: [["Position", "Size", "Colour", "Shape"]],
    vis_name: "Area Select",
    vis_usage: ["Game"],
    vis_position: [
      {
        screen_relativity: "Screen",
        screen_position: ["Bottom", "Middle"],
        coords: "World",
      },
    ],
    vis_visibility: [["Global", False]],
    notes: [],
  },
  {
    game_id: "71",
    screenshot_id: "1",
    vis_id: "g2",
    data: [[{ data_value: "Total moons", data_type: "Quantitative" }]],
    marks: [["Rectangle", "Text"]],
    channels: [["Text"]],
    vis_name: "Moons Collected",
    vis_usage: ["Game"],
    vis_position: [
      {
        screen_relativity: "Screen",
        screen_position: ["Top", "Right"],
        coords: "Screen",
      },
    ],
    vis_visibility: [["Global", False]],
    notes: [
      "DATA VALUE: The total amount of moons collected across all stages",
      "ENCODING: MARK: Rectangle box counter with text (digit) and symbol",
    ],
  },
  {
    game_id: "71",
    screenshot_id: "2",
    vis_id: "l1a",
    data: [[{ data_value: "Player location", data_type: "Spatial" }]],
    marks: [["Symbol", "Arc"]],
    channels: [["Position", "Angle", "Shape"]],
    vis_name: "Player Pointer",
    vis_usage: ["Player"],
    vis_position: [
      {
        screen_relativity: "Relative",
        screen_position: "Based on player position",
        coords: "World",
      },
    ],
    vis_visibility: [["Local", False]],
    notes: [
      "DATA VALUE: Current location of player, orientation",
      "DATA TYPE: SPATIAL",
      "ENCODING: MARK: Symbols with POV range, arced AREA",
      "Where in space is Mario",
      "Which direction is Mario facing",
      "M for it’s a me Mario",
    ],
  },
  {
    game_id: "71",
    screenshot_id: "2",
    vis_id: "l1b",
    data: [[{ data_value: "viewpoint name", data_type: "Spatial" }]],
    marks: [["Symbol", "Text"]],
    channels: [["Position", "Text", "Shape"]],
    vis_name: "Active hovered viewpoint",
    vis_usage: ["Environment"],
    vis_position: [
      {
        screen_relativity: "Relative",
        screen_position: "Location of selected",
        coords: "World",
      },
    ],
    vis_visibility: [["Local", False]],
    notes: [
      "The name of the viewpoint with instructions on button control to fast warp to that area.",
    ],
  },
  {
    game_id: "71",
    screenshot_id: "2",
    vis_id: "l1c",
    data: [[{ data_value: "Next objective pos", data_type: "Spatial" }]],
    marks: [["Symbol"]],
    channels: [["Position"], ["Shape"]],
    vis_name: "Next objective",
    vis_usage: ["Environment"],
    vis_position: [
      {
        screen_relativity: "Relative",
        screen_position: "Location of the main objective",
        coords: "World",
      },
    ],
    vis_visibility: [["Local", False]],
    notes: [],
  },
  {
    game_id: "71",
    screenshot_id: "3",
    vis_id: "g1",
    data: [[{ data_value: "Total coins", data_type: "Quantitative" }]],
    marks: [["Symbol", "Text"]],
    channels: [["Text", "Shape"]],
    vis_name: "Coin counter",
    vis_usage: ["Game"],
    vis_position: [
      {
        screen_relativity: "Screen",
        screen_position: ["Top", "Left"],
        coords: "Camera",
      },
    ],
    vis_visibility: [["Global", False]],
    notes: [],
  },
  {
    game_id: "71",
    screenshot_id: "3",
    vis_id: "l1",
    data: [[{ data_value: "Total coins", data_type: "Quantitative" }]],
    marks: [["Symbol", "Text"]],
    channels: [["Text", "Shape"]],
    vis_name: "Currency counter",
    vis_usage: ["Player"],
    vis_position: [
      {
        screen_relativity: "Screen",
        screen_position: ["Top", "Left"],
        coords: "Camera",
      },
    ],
    vis_visibility: [["Local", False]],
    notes: [],
  },
  {
    game_id: "71",
    screenshot_id: "3",
    vis_id: "l2",
    data: [[{ data_value: "Total moons", data_type: "Quantitative" }]],
    marks: [["Symbol"]],
    channels: [["Shape"], ["Position"]],
    vis_name: "Moon counter",
    vis_usage: ["Player"],
    vis_position: [
      {
        screen_relativity: "Screen",
        screen_position: ["Top", "Left"],
        coords: "Camera",
      },
    ],
    vis_visibility: [["Local", False]],
    notes: [
      "The visualization represents the total amount of moons collected and remaining.",
      "Dotted line circle represents the empty slot and denotes how many collected.",
    ],
  },
  {
    game_id: "71",
    screenshot_id: "3",
    vis_id: "le3",
    data: [[{ data_value: "Health", data_type: "Quantitative" }]],
    marks: [["Arc", "Rule", "Text"]],
    channels: [["Angle", "Text", "Hue"]],
    vis_name: "Health Meter",
    vis_usage: ["Player"],
    vis_position: [
      {
        screen_relativity: "Relative",
        screen_position: "above character when damaged",
        coords: "Camera",
      },
    ],
    vis_visibility: [["Local", False]],
    notes: [
      "Cyclic bar with text (QUANTITATIVE value) in the middle.",
      "Dotted line circle represents the empty slot.",
      "Number value of health points left.",
      "Blue: extra health points. Green: Good amount of health left (more than 50%). Yellow: Moderate amount of health left (less than 50%). Red: Low amount of health left (less than 25%).",
    ],
  },
  {
    game_id: "71",
    screenshot_id: "3",
    vis_id: "l4",
    data: [[{ data_value: "Player orientation", data_type: "Ordinal" }]],
    marks: [["Path"]],
    channels: [["Angle"]],
    vis_name: "Compass",
    vis_usage: ["Player"],
    vis_position: [
      {
        screen_relativity: "Screen",
        screen_position: ["Top", "Right"],
        coords: "Camera",
      },
    ],
    vis_visibility: [["Local", False]],
    notes: ["Compass illustration with arced AREA"],
  },
  {
    game_id: "71",
    screenshot_id: "4",
    vis_id: "le1",
    data: [[{ data_value: "Direction", data_type: "Spatial" }]],
    marks: [["Symbol", "Path"]],
    channels: [["Position", "Length", "Angle", "Animation"]],
    vis_name: "Chain Chomps Directional Line",
    vis_usage: ["Player"],
    vis_position: [
      {
        screen_relativity: "Relative",
        screen_position: "player",
        coords: "World",
      },
    ],
    vis_visibility: [["Local", False]],
    notes: [
      "DATA VALUE: Direction/final end point of Chain Chomp release",
      "DATA TYPE: SPATIAL",
      "ENCODING: MARK: Repeating chevron SYMBOLS along a PATH",
      "CHANNEL 1: Position Where is endpoint",
      "CHANNEL 2: Length Generally estimate distance travelled",
      "CHANNEL 3: Angle",
      "CHANNEL 4: Animation Arrows slowly animated in a loop towards the direction it’s facing",
    ],
  },
];
