[
    ,
{'game_id': '69',
 'screenshot_id': '1',
 'vis_id': 'l1',
 'data': [{'data_value': 'Players health', 'data_type': 'Quantitative'},
  {'data_value': 'money (geo)', 'data_type': 'Quantitative'},
  {'data_value': 'healing (circle)', 'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Text', 'Symbol', 'Circle'],
 'channels': [['Length'], ['Luminance'], ['Text'], ['Length']],
 'vis_name': 'Health bar and currency',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Healing bar (circle) slowly fills up, once full, players can heal.']},
 {'game_id': '69',
 'screenshot_id': '2',
 'vis_id': 'l1',
 'data': [{'data_value': 'Battle timer', 'data_type': 'Nominal'}],
 'marks': ['Text'],
 'channels': [['Text']],
 'vis_name': 'Boss battle',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Right'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Time = 0',
  'The boss’s name will appear when player is in that area']},
  {'game_id': '69',
 'screenshot_id': '3',
 'vis_id': 'l1',
 'data': [{'data_value': 'Achievement', 'data_type': 'Nominal'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Shape'], ['Text']],
 'vis_name': 'Achievement',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Middle', 'Left'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Appears when completing an achievement',
  'Each achievement has its own icon']},
  {'game_id': '69',
 'screenshot_id': '3',
 'vis_id': 'l2',
 'data': [{'data_value': 'Item gained', 'data_type': 'Nominal'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Shape', ['Hue', 'Saturation', 'Lightness']], ['Text']],
 'vis_name': 'Item gained',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Left'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Pops up when players find an item']},
 {'game_id': '69',
 'screenshot_id': '4',
 'vis_id': 'l1',
 'data': [{'data_value': 'Charm selected', 'data_type': 'Nominal'},
  {'data_value': 'Slot number', 'data_type': 'Ordinal'},
  {'data_value': 'Notch count', 'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Text', 'Circle'],
 'channels': [['Shape', ['Hue', 'Saturation', 'Lightness']], ['Length']],
 'vis_name': 'Equipment',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['The characters main thing is using different charms to match their strategy and optimize gameplay.',
  'Each charm has a cost and players can only equip a certain amount of charms depending on their available slot & notches (the cost of each charm).',
  'Identify used vs. remaining notches to know if charms can be equipped or not.',
  'The glowing circle for how many more notches players have, (the one with no glow means its already used up).',
  "The circle in the equipped section means players can still equip 1 more charm (if they also have enough notches players don't have yet)."]},
{'game_id': '69',
 'screenshot_id': '4',
 'vis_id': 'l2',
 'data': [{'data_value': 'charm found', 'data_type': 'Nominal'},
  {'data_value': 'slot', 'data_type': 'Ordinal'}],
 'marks': ['Symbol'],
 'channels': [['Position'],
  ['Shape', ['Hue', 'Saturation', 'Lightness']],
  ['Length']],
 'vis_name': 'Available charms',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['All the charms (equipment) the player owns is visible here, each has their own thing.',
  'Charms that aren’t discovered yet just have a circle occupying their space.']},
  {'game_id': '69',
 'screenshot_id': '4',
 'vis_id': 'l3a',
 'data': [{'data_value': 'Player cursor', 'data_type': 'Spatial'}],
 'marks': ['Area', 'Symbol'],
 'channels': [['Position']],
 'vis_name': 'Charm selector',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Player controlled',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Hovering over the charm to get more info from it',
  'The white border around the charm + the blue glow around the charm']},
  {'game_id': '69',
 'screenshot_id': '4',
 'vis_id': 'l3b',
 'data': [{'data_value': 'Name', 'data_type': 'Nominal'},
  {'data_value': 'details', 'data_type': 'Nominal'},
  {'data_value': 'notch cost', 'data_type': 'Quantitative'}],
 'marks': ['Image', 'Text', 'Circle'],
 'channels': [['Shape', ['Hue', 'Saturation', 'Lightness']],
  ['Text'],
  ['Length']],
 'vis_name': 'Charm details',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Middle', 'Right'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Info on what the charm selected from (3a) does and how much it costs to equip t']},
 {'game_id': '69',
 'screenshot_id': '4',
 'vis_id': 'l4',
 'data': [{'data_value': 'charms equipped', 'data_type': 'Nominal'}],
 'marks': ['Circle'],
 'channels': [['Lightness']],
 'vis_name': 'Equipped charm',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'player controlled',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['DATA VALUE: The charms the player has equipped']},
 {'game_id': '69',
 'screenshot_id': '5',
 'vis_id': 'l1',
 'data': [{'data_value': 'By entering specific parts',
   'data_type': 'Spatial'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Angle'], ['Text']],
 'vis_name': 'Adjacent areas',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'area',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['The arrow above the text means that it’ll bring the player to a diff area']},
 {'game_id': '69',
 'screenshot_id': '5',
 'vis_id': 'l2',
 'data': [{'data_value': 'Place name', 'data_type': 'Nominal'},
  {'data_value': 'position', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Shape', 'Hue']],
 'vis_name': 'Map pins',
 'vis_usage': ['Environment'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Point of Interest',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Places of interest on the map',
  'Different icons & color type = different things (eg. bench --> save, orange icons --> different stores)']},
  {'game_id': '69',
 'screenshot_id': '5',
 'vis_id': 'l3',
 'data': [{'data_value': 'Boss type, location', 'data_type': 'Nominal'},
  {'data_value': 'Boss type, location', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Size'], ['Shape']],
 'vis_name': 'Final boss battle',
 'vis_usage': ['Game'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'on their spot in the map',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Unlocking this area unlocks the final boss (and later lets players repeat some old miniboss fights)',
  'Higher attention in hierarchy draws player towards important event']}
    ,

{'game_id': '70',
 'screenshot_id': '1',
 'vis_id': 'l1a',
 'data': [{'data_value': 'Mission location', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Luminance'], ['Shape']],
 'vis_name': 'Mission Location',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'direction of objective',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '70',
 'screenshot_id': '1',
 'vis_id': 'l1b',
 'data': [{'data_value': 'Mission location', 'data_type': 'Spatial'}],
 'marks': ['Line', 'Symbol', 'Text'],
 'channels': [['Position'], ['Shape'], ['Text']],
 'vis_name': 'Mission distance',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Middle'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Precisely identify where the icon is located determines where the player needs to go (left, right, or forward)',
  'What players need to look at to know where to go']},
  {'game_id': '70',
 'screenshot_id': '2',
 'vis_id': 'l1',
 'data': [{'data_value': 'Objective time remaining',
   'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Text']],
 'vis_name': 'Timer',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Middle'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '70',
 'screenshot_id': '3',
 'vis_id': 'l1',
 'data': [{'data_value': 'Where the player is located',
   'data_type': 'Spatial'}],
 'marks': ['Text'],
 'channels': [['Luminance'], ['Text']],
 'vis_name': 'Location',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': ['Local', False],
 'notes': ['Identify selected state', 'Precisely get location']},
 {'game_id': '70',
 'screenshot_id': '3',
 'vis_id': 'l2a',
 'data': [{'data_value': 'Mission Location', 'data_type': 'Spatial'},
  {'data_value': 'Quest name/id', 'data_type': 'Ordinal'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Position'], ['Shape', ['Hue']]],
 'vis_name': 'Mission Location',
 'vis_usage': ['Game'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'mission location',
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Where a mission is located, what is it.',
  'Depending on the mission, I think the color also changes.']},
  {'game_id': '70',
 'screenshot_id': '3',
 'vis_id': 'l2b',
 'data': [{'data_value': 'Mission goals', 'data_type': 'Nominal'},
  {'data_value': 'Progress', 'data_type': 'Quantitative'}],
 'marks': ['Rectangle', 'Symbol', 'Text'],
 'channels': [['Text'], ['Shape', ['Saturation', 'Hue']]],
 'vis_name': 'Mission details',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Tells players which button on the controller to click to do specific actions',
  'Also helps differentiate the heading with body']},
  {'game_id': '70',
 'screenshot_id': '3',
 'vis_id': 'l1',
 'data': [{'data_value': 'Player position', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Shape', 'Luminance']],
 'vis_name': 'Player position',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'mission',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Slight glow around the icon']},
 {'game_id': '70',
 'screenshot_id': '4',
 'vis_id': 'l1',
 'data': [{'data_value': 'Where the player is located within whole city',
   'data_type': 'Spatial'}],
 'marks': ['Path', 'Line', 'Text'],
 'channels': [['Saturation', 'Luminance'], ['Position'], ['Text']],
 'vis_name': 'Player position',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Player location',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['The area that the player is in is coloured in',
  'The pop-up with the text of where the player is at has a blue bg colour too to help it show up']},
  {'game_id': '70',
 'screenshot_id': '5',
 'vis_id': 'le1',
 'data': [{'data_value': 'Status effect', 'data_type': 'Nominal'}],
 'marks': ['Text'],
 'channels': [['Text']],
 'vis_name': 'Special Attack used',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above player character',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '70',
 'screenshot_id': '5',
 'vis_id': 'l2',
 'data': [{'data_value': 'Enemy health', 'data_type': 'Quantitative'}],
 'marks': ['Rectangle'],
 'channels': [['Length'], [['Hue']], ['Text']],
 'vis_name': 'Enemy Health Bar',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above enemy',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Bar under the health is for a status effect, fills up as the enemy gets hit.',
  'The damage they receive is in red and it’ll deplete the bar by that much.']},
  {'game_id': '70',
 'screenshot_id': '5',
 'vis_id': 'l3',
 'data': [{'data_value': 'Target specific enemy', 'data_type': 'Nominal'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Text']],
 'vis_name': 'Targeting enemy',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Middle of enemy',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Players can target a specific enemy to fight with',
  'Says locked on']},
  {'game_id': '70',
 'screenshot_id': '6',
 'vis_id': 'l1',
 'data': [{'data_value': 'Damage from enemy', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Hue'], ['Text']],
 'vis_name': 'Damage received',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above the character',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['DATA TYPE: QUANTITATIVE',
  'ENCODING: Distinguish health update from heal',
  'Get precise value']},
  {'game_id': '70',
 'screenshot_id': '6',
 'vis_id': 'le2',
 'data': [{'data_value': 'Status effect (pressure)', 'data_type': 'Nominal'}],
 'marks': ['Text'],
 'channels': [['Length'], ['Text']],
 'vis_name': 'Pressure effect',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Under enemy health bar',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['When players hit a critical attack / uses a magic element the enemy is weak to, this effect can happen.',
  'The bar slowly builds up to, when full it’ll change the effect to staggered.']},
  {'game_id': '70',
 'screenshot_id': '7',
 'vis_id': 'le1',
 'data': [{'data_value': 'Healing amount', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Hue'], ['Text']],
 'vis_name': 'Healing',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Middle of player character',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Differentiate from damage received.', 'Get precise value.']},
 {'game_id': '70',
 'screenshot_id': '8',
 'vis_id': 'le1',
 'data': [{'data_value': 'Boss special move', 'data_type': 'Nominal'}],
 'marks': ['Text'],
 'channels': [['Text'], ['Lightness']],
 'vis_name': 'Boss special action',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above the enemy health bar, sometimes overlapping',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Bosses always have a special move that they can do, when that happens, a text above them will appear telling players it happening to give them time to dodge.',
  'Ensures the player notices it']},
  {'game_id': '70',
 'screenshot_id': '8',
 'vis_id': 'le2',
 'data': [{'data_value': 'Physical damage', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Text'], ['Hue']],
 'vis_name': 'Damage dealt',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'wherever the attack hits the enemy',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Damage dealt by the characters from melee attacks (or guns!)']},
 {'game_id': '70',
 'screenshot_id': '8',
 'vis_id': 'l3',
 'data': [{'data_value': 'Health, MP, ATB, Limit',
   'data_type': 'Quantitative'}],
 'marks': ['Text', 'Area'],
 'channels': [['Text'], ['Length'], ['Hue', 'Saturation', 'Lightness']],
 'vis_name': 'Player stats',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Right'],
   'coords': 'Screen'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Players can see info on the characters in their team. The one the player is controlling will always have their stats card be a bit bigger and below all the other ones.',
  'Shows how much of each thing the players have (eg. how much health, how much mp, the ATB value).',
  'Differentiate each thing with each other, helps it stand out.']},
  {'game_id': '70',
 'screenshot_id': '9',
 'vis_id': 'l1',
 'data': [{'data_value': 'Stagger progress', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Length'], ['Text']],
 'vis_name': 'Staggered effect',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Under the enemy’s health bar',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Happens when the bar under the health is filled up. Increases the chance of enemies getting stunned + increases damage received.']},
 {'game_id': '70',
 'screenshot_id': '9',
 'vis_id': 'l1',
 'data': [{'data_value': 'Magic damage type, amount', 'data_type': 'Nominal'},
  {'data_value': 'Magic damage type, amount', 'data_type': 'Quantitative'}],
 'marks': ['Text'],
 'channels': [['Text'], ['Hue']],
 'vis_name': 'Magic damage dealt',
 'vis_usage': ['Enemy'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Above the enemy getting attacked',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Damage dealt by the characters from spells']}
    ,
{'game_id': '71',
 'screenshot_id': '1',
 'vis_id': 'g1',
 'data': [{'data_value': 'Areas available', 'data_type': 'Ordinal'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Position'], ['Length'], ['Hue'], ['Shape']],
 'vis_name': 'Area Select',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Bottom', 'Middle'],
   'coords': 'World'}],
 'vis_visibility': [['Global', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '1',
 'vis_id': 'g2',
 'data': [{'data_value': 'Total moons collected',
   'data_type': 'Quantitative'}],
 'marks': ['Rectangle', 'Text'],
 'channels': [['Text']],
 'vis_name': 'Total moons collected',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Right'],
   'coords': 'Camera'}],
 'vis_visibility': [['Global', False]],
 'notes': ['The total amount of moons collected across all stages']},
 {'game_id': '71',
 'screenshot_id': '2',
 'vis_id': 'l1a',
 'data': [{'data_value': 'Current location of player', 'data_type': 'Spatial'},
  {'data_value': 'orientation', 'data_type': 'Spatial'}],
 'marks': ['Symbol', 'Area'],
 'channels': [['Position'], ['Angle'], ['Shape']],
 'vis_name': 'Player Pointer',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Based on player position',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '2',
 'vis_id': 'l1b',
 'data': [{'data_value': 'Name of viewpoint',
   'data_type': 'Spatial'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Position'], ['Text'], ['Shape']],
 'vis_name': 'Active hovered viewpoint',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Location of selected',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['The name of the viewpoint with instructions on button control to fast warp to that area.']},
 {'game_id': '71',
 'screenshot_id': '2',
 'vis_id': 'l1c',
 'data': [{'data_value': 'Next objective position', 'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Shape']],
 'vis_name': 'Next objective',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Location of the main objective',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '3',
 'vis_id': 'g1',
 'data': [{'data_value': 'Total number of coins',
   'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Text'], ['Shape']],
 'vis_name': 'Global Coin counter',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'World'}],
 'vis_visibility': [['Global', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '3',
 'vis_id': 'l1',
 'data': [{'data_value': 'Total number of local...coins owned',
   'data_type': 'Quantitative'}],
 'marks': ['Symbol', 'Text'],
 'channels': [['Text'], ['Shape']],
 'vis_name': 'Local Currency counter',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '3',
 'vis_id': 'l2',
 'data': [{'data_value': 'Total amount of moons collected and remaining',
   'data_type': 'Quantitative'}],
 'marks': ['Symbol'],
 'channels': [['Shape'], ['Position']],
 'vis_name': 'Moon counter',
 'vis_usage': [],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Left'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '3',
 'vis_id': 'le3',
 'data': [{'data_value': 'Health', 'data_type': 'Quantitative'}],
 'marks': ['Arc', 'Text'],
 'channels': [['Angle'], ['Text'], ['Hue']],
 'vis_name': 'Health Point Meter',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'above character when damaged',
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': ['Cyclic bar with text (QUANTITATIVE value) in the middle.',
  'Dotted line circle represents the empty slot.',
  'Number value of health points left.',
  'Blue: extra health points.',
  'Green: Good amount of health left (more than 50%).',
  'Yellow: Moderate amount of health left (less than 50%).',
  'Red: Low amount of health left (less than 25%).']},
  {'game_id': '71',
 'screenshot_id': '3',
 'vis_id': 'l4',
 'data': [{'data_value': 'Player orientation', 'data_type': 'Ordinal'}],
 'marks': ['Area'],
 'channels': [['Angle']],
 'vis_name': 'Compass',
 'vis_usage': ['Player'],
 'vis_position': [{'screen_relativity': 'Screen',
   'screen_position': ['Top', 'Right'],
   'coords': 'Camera'}],
 'vis_visibility': [['Local', False]],
 'notes': []},
 {'game_id': '71',
 'screenshot_id': '4',
 'vis_id': 'le1',
 'data': [{'data_value': 'Direction/final end point of Chain Chomp release',
   'data_type': 'Spatial'}],
 'marks': ['Symbol'],
 'channels': [['Position'], ['Length'], ['Angle'], ['Animation']],
 'vis_name': 'Chain Chomps Directional Line',
 'vis_usage': ['Game'],
 'vis_position': [{'screen_relativity': 'Relative',
   'screen_position': 'Player',
   'coords': 'World'}],
 'vis_visibility': [['Local', False]],
 'notes': ['MARK: Repeating chevron SYMBOLS along a PATH',
  'Arrows slowly animated in a loop towards the direction it’s facing']}
]